# TODO: Change app-name
# :%s/app-name/YourProjectAppName/g
before:
  hooks:
    - go mod tidy
    - go generate ./...

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

builds:
  - id: "app-name"
    main: ./src/
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm64
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}

brews:
  - name: app-name
    repository:
      owner: HidemaruOwO
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
