name: "Lint and Format"

on:
  workflow_dispatch: ~
  push:
    paths:
      - "src/**"
    branches:
      - "develop"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract branch name
        # actionlint ignore=SC2086
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        shell: bash
        id: extract_branch
      - name: Setup
        run: echo "Set up your programing language here."
        # uses: actions/setup-go@v2
      - name: Install formatter
        run: echo "Install formatter (Example; npm install prettier)"

      - name: Format code
        run: echo "Run formatter (Example; prettier .)"

      - run: git config --global user.name "github-actions"
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git stash
      - run: git checkout ${{ steps.extract_branch.outputs.branch }} && git pull
      - run: git stash pop || true

      - name: Commit
        # actionlint ignore=SC2015
        run: git add -u && git commit -m '👀 Format Code' || true

      - name: Push
        run: git push --set-upstream --force origin ${{ steps.extract_branch.outputs.branch }}
