name: Test CLI

on:
  push:

permissions:
  statuses: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        id: test
        continue-on-error: true
        run: |
          echo "Write Test here"
          exit 1
      - name: Set Check Status Success
        uses: Sibz/github-status-action@v1
        if: success() && steps.test.outputs.result == 'success'
        with:
          context: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success
      - name: Set Check Status Failure
        uses: Sibz/github-status-action@v1
        if: failure() && steps.test.outcome == 'failure'
        with:
          context: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: failure

      - name: Fail
        uses: Sibz/action-always-fail@v1.0.1
        if: failure() && steps.test.outcome == 'failure'
