name: Test CLI

on:
  push:

permissions:
  statuses: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: |
          echo "Write Test here"
          exit 1
      - name: Set Check Status Success
        uses: Sibz/github-status-action@v1
        with:
          context: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success
      - name: fail
        uses: Sibz/action-always-fail@v1.0.1
        if: steps.stepId.outputs.result != 'failure'
